name: 'mockoon-docs'
description: 'Create mockoon docs'
inputs:
  mockoon-json-file:
    description: 'The JSON file of the Mockoon mock'
    required: true
  github-token:
    description: 'GitHub token which allows the action to comment on PRs'
    required: true
outputs:
  mockoon-docs-md:
    description: 'Markdown version of Mockoon mock'
runs:
  using: 'node18'
  main: 'index.js'
