#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint

# Convert line endings to LF
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.ts" "*.json" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "Ensuring UNIX line endings..."

# Convert to Unix line endings
for FILE in $FILES; do
  dos2unix "$FILE"
  git add "$FILE"
done